// <auto-generated />
namespace lamia12771.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ValidationUpdates : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ValidationUpdates));
        
        string IMigrationMetadata.Id
        {
            get { return "202609051951415_ValidationUpdates"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
